name: Playwright E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: "Test on ${{ matrix.os }} - ${{ matrix.browser }}"
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        browser: [chromium, firefox, webkit]
        exclude:
          - os: windows-latest
            browser: webkit
          - os: windows-latest
            browser: firefox
          - os: macos-latest
            browser: firefox
        include:
          - os: windows-latest
            browser: edge

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: |
          npx playwright install --with-deps
          if [ "${{ matrix.browser }}" = "edge" ]; then
            npx playwright install msedge;
          fi
        shell: bash

      - name: Start xvfb
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          nohup Xvfb :99 -screen 0 1920x1080x24 &
          export DISPLAY=:99

      - name: Run tests
        env:
          PW_USERNAME: ${{ secrets.PW_USERNAME }}
          PW_PASSWORD: ${{ secrets.PW_PASSWORD }}
        run: npx playwright test --project=${{ matrix.browser }}

      - name: Upload test artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: report-${{ matrix.os }}-${{ matrix.browser }}
          path: |
            playwright-report/
            test-results/
            reports/
          retention-days: 30

  merge-reports:
    name: "Merge All Reports - Global"
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Download all reports
        uses: actions/download-artifact@v4
        with:
          path: all-reports

      - name: Install Playwright
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Merge Playwright reports
        run: |
          mkdir merged-report
          npx playwright merge-reports all-reports/**/playwright-report --output=merged-report

      - name: Upload merged report
        uses: actions/upload-artifact@v4
        with:
          name: global-merged-report
          path: merged-report/
          retention-days: 30
